pipeline {
    agent any
    environment {
        GITHUB_STATUS_URL = "https://github01.hclpnp.com/api/v3/repos/UXUIAssets/patron-react-dev/statuses"
        STATUS_NAME = "ci-eslint/jenkins"
    }
    tools {nodejs "nodejs-path"}
    stages {
        stage('Checkout') {
            steps {
                script{
                    cleanWs()
                    checkout(
                        [
                            $class: 'GitSCM', 
                            branches: [[name: "${Commit_ID}"]], 
                            extensions: [[$class: 'WipeWorkspace']],
                            submoduleCfg: [], 
                            userRemoteConfigs: [
                                [
                                    credentialsId: 'gupta-ma', 
                                    url: 'https://github01.hclpnp.com/UXUIAssets/patron-react-dev.git'
                                ]
                            ]
                        ]
                    )
                }
            }
        }
        stage('Install') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh 'npm run eslint-test'
            }
        }
    }
    post {
        failure {
            sh label: '', script: '''curl "$GITHUB_STATUS_URL/$Commit_ID" \\
                -H "Content-Type: application/json" \\
                -H "Authorization: token $GITHUB_TOKEN" \\
                -X POST \\
                -d "{\\"state\\": \\"failure\\",\\"context\\": \\"$STATUS_NAME\\", \\"description\\": \\"Jenkins\\", \\"target_url\\": \\"${BUILD_URL}console\\"}"'''
        }
        success {
            sh label: '', script: '''curl "$GITHUB_STATUS_URL/$Commit_ID" \\
                -H "Content-Type: application/json" \\
                -H "Authorization: token $GITHUB_TOKEN" \\
                -X POST \\
                -d "{\\"state\\": \\"success\\",\\"context\\": \\"$STATUS_NAME\\", \\"description\\": \\"Jenkins\\", \\"target_url\\": \\"${BUILD_URL}console\\"}"'''
        }
    }
}
